# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-14 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'N/A', max_length=50)),
                ('email_id', models.CharField(default=b'N/A', max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('gender', models.CharField(default=b'Common', max_length=6)),
                ('password', models.CharField(default=b'', max_length=30)),
                ('salt', models.CharField(default=b'', max_length=20)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
